-- Scenario definitions (seeded from JSON but stored here for querying)
CREATE TABLE scenarios (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    steps JSONB NOT NULL,
    seeded_bugs JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Each execution of a scenario
CREATE TABLE runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    scenario_id TEXT REFERENCES scenarios(id),
    status TEXT NOT NULL DEFAULT 'pending',  -- pending, running, passed, failed, error
    active_bugs JSONB DEFAULT '[]',
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Individual steps within a run
CREATE TABLE run_steps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id UUID REFERENCES runs(id) ON DELETE CASCADE,
    step_index INTEGER NOT NULL,
    name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',  -- pending, running, passed, failed, skipped
    screenshot_path TEXT,
    console_errors JSONB DEFAULT '[]',
    network_errors JSONB DEFAULT '[]',
    dom_snapshot TEXT,
    detail TEXT,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ
);

-- Triage reports generated by Nova 2 Lite
CREATE TABLE triage_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id UUID REFERENCES runs(id) ON DELETE CASCADE,
    failure_category TEXT,
    root_cause TEXT,
    confidence REAL,
    repro_steps JSONB,
    suggested_fix TEXT,
    jira_title TEXT,
    jira_description TEXT,
    severity TEXT,
    raw_response JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_runs_scenario ON runs(scenario_id);
CREATE INDEX idx_run_steps_run ON run_steps(run_id);
CREATE INDEX idx_triage_run ON triage_reports(run_id);
